/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:648: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:648: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.8/distutils/command/install.py", line 601, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install_scripts.py", line 52, in run
    for args in writer.get_args(dist, cmd.as_header()):
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py", line 2111, in get_args
    cls._ensure_safe_name(name)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py", line 2124, in _ensure_safe_name
    raise ValueError("Path separators not allowed in script names")
ValueError: Path separators not allowed in script names
